// Part of the Carbon Language project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// AUTOUPDATE
// TIP: To test this file alone, run:
// TIP:   bazel test //toolchain/testing:file_test --test_arg=--file_tests=toolchain/parse/testdata/alias/fail_syntax.carbon
// TIP: To dump output, run:
// TIP:   bazel run //toolchain/testing:file_test -- --dump_output --file_tests=toolchain/parse/testdata/alias/fail_syntax.carbon

// CHECK:STDERR: fail_syntax.carbon:[[@LINE+3]]:1-5: error: `alias` introducer should be followed by a name [ExpectedDeclName]
// CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:1-5: note: expected name after this token [DeclNameGoesAfter]
// CHECK:STDERR:
alias = b;

// CHECK:STDERR: fail_syntax.carbon:[[@LINE+3]]:7: error: `alias` requires a `=` for the source [ExpectedAliasInitializer]
// CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:7: note: expected `=` after this token [AliasEqualGoesAfter]
// CHECK:STDERR:
alias a b;

// CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:10: error: expected expression [ExpectedExpr]
// CHECK:STDERR:
alias a =;

// CHECK:STDERR: fail_syntax.carbon:[[@LINE+3]]:7: error: `alias` requires a `=` for the source [ExpectedAliasInitializer]
// CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:7: note: expected `=` after this token [AliasEqualGoesAfter]
// CHECK:STDERR:
alias a;

// CHECK:STDERR: fail_syntax.carbon:[[@LINE+3]]:1-5: error: `alias` introducer should be followed by a name [ExpectedDeclName]
// CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:1-5: note: expected name after this token [DeclNameGoesAfter]
// CHECK:STDERR:
alias =;

// CHECK:STDERR: fail_syntax.carbon:[[@LINE+3]]:7: error: `alias` requires a `=` for the source [ExpectedAliasInitializer]
// CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:7: note: expected `=` after this token [AliasEqualGoesAfter]
// CHECK:STDERR:
alias a b c = d;

// CHECK:STDERR: fail_syntax.carbon:[[@LINE+3]]:11: error: `alias` declarations must end with a `;` [ExpectedDeclSemi]
// CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:11: note: expected `;` after this token [DeclSemiGoesAfter]
// CHECK:STDERR:
alias a = b c d;

fn F() {
  // CHECK:STDERR: fail_syntax.carbon:[[@LINE+3]]:3-7: error: `alias` introducer should be followed by a name [ExpectedDeclName]
  // CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:3-7: note: expected name after this token [DeclNameGoesAfter]
  // CHECK:STDERR:
  alias;

  // CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:12: error: expected expression [ExpectedExpr]
  // CHECK:STDERR:
  alias a =;

  alias a =
// CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:1: error: expected expression [ExpectedExpr]
// CHECK:STDERR:
}

// CHECK:STDERR: fail_syntax.carbon:[[@LINE+3]]:11: error: `alias` declarations must end with a `;` [ExpectedDeclSemi]
// CHECK:STDERR: fail_syntax.carbon:[[@LINE+2]]:11: note: expected `;` after this token [DeclSemiGoesAfter]
// CHECK:STDERR:
alias a = b

// CHECK:STDOUT: - filename: fail_syntax.carbon
// CHECK:STDOUT:   ╭─FileStart ''
// CHECK:STDOUT:   │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ ├─InvalidParse '=' has_error
// CHECK:STDOUT:   ├─Alias ';' has_error
// CHECK:STDOUT:   │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ ├─IdentifierNameNotBeforeSignature 'a'
// CHECK:STDOUT:   ├─Alias ';' has_error
// CHECK:STDOUT:   │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ ├─IdentifierNameNotBeforeSignature 'a'
// CHECK:STDOUT:   │ ├─AliasInitializer '='
// CHECK:STDOUT:   │ ├─InvalidParse ';' has_error
// CHECK:STDOUT:   ├─Alias ';' has_error
// CHECK:STDOUT:   │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ ├─IdentifierNameNotBeforeSignature 'a'
// CHECK:STDOUT:   ├─Alias ';' has_error
// CHECK:STDOUT:   │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ ├─InvalidParse '=' has_error
// CHECK:STDOUT:   ├─Alias ';' has_error
// CHECK:STDOUT:   │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ ├─IdentifierNameNotBeforeSignature 'a'
// CHECK:STDOUT:   ├─Alias ';' has_error
// CHECK:STDOUT:   │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ ├─IdentifierNameNotBeforeSignature 'a'
// CHECK:STDOUT:   │ ├─AliasInitializer '='
// CHECK:STDOUT:   │ ├─IdentifierNameExpr 'b'
// CHECK:STDOUT:   ├─Alias ';' has_error
// CHECK:STDOUT:   │   ╭─FunctionIntroducer 'fn'
// CHECK:STDOUT:   │   ├─IdentifierNameMaybeBeforeSignature 'F'
// CHECK:STDOUT:   │   │ ╭─ExplicitParamListStart '('
// CHECK:STDOUT:   │   ├─ExplicitParamList ')'
// CHECK:STDOUT:   │ ╭─FunctionDefinitionStart '{'
// CHECK:STDOUT:   │ │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ │ ├─InvalidParse ';' has_error
// CHECK:STDOUT:   │ ├─Alias ';' has_error
// CHECK:STDOUT:   │ │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ │ ├─IdentifierNameNotBeforeSignature 'a'
// CHECK:STDOUT:   │ │ ├─AliasInitializer '='
// CHECK:STDOUT:   │ │ ├─InvalidParse ';' has_error
// CHECK:STDOUT:   │ ├─Alias ';' has_error
// CHECK:STDOUT:   │ │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ │ ├─IdentifierNameNotBeforeSignature 'a'
// CHECK:STDOUT:   │ │ ├─AliasInitializer '='
// CHECK:STDOUT:   │ │ ├─InvalidParse '}' has_error
// CHECK:STDOUT:   │ ├─Alias '=' has_error
// CHECK:STDOUT:   ├─FunctionDefinition '}'
// CHECK:STDOUT:   │ ╭─AliasIntroducer 'alias'
// CHECK:STDOUT:   │ ├─IdentifierNameNotBeforeSignature 'a'
// CHECK:STDOUT:   │ ├─AliasInitializer '='
// CHECK:STDOUT:   │ ├─IdentifierNameExpr 'b'
// CHECK:STDOUT:   ├─Alias 'b' has_error
// CHECK:STDOUT:   ├─FileEnd ''
// CHECK:STDOUT:   (root)
